variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  SUFFIX: $CI_PIPELINE_ID

stages:
  - build
  - test
  - push

registry_login:
  stage: build
  script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}

build_image:
  stage: build
  script:
    - docker build -t ${IMAGE_TAG} .

test_image:
  stage: test
  script:
    - docker build -t ${IMAGE_TAG}_test --build-arg image=${IMAGE_TAG} -f DockerfileTest .

push_image:
  stage: push
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
    - docker push ${IMAGE_TAG}
